

- name: "HIGH | V-13733 | Server Side Includes (SSIs) must be run with execution capability disabled."
  lineinfile:
    path:     "{{ httpd_conf_file }}"
    regexp:   '(.*)Options(.*)(\sIncludes\s)(.*)'
    line:     '\1Options \2\4'
    backrefs: yes
  tags:
    - cat1
    - V-13733

