
- name: "HIGH | V-13733 | Server Side Includes (SSIs) must be run with execution capability disabled. Add '-IncludesNoExec'"
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   '^(\s+)Options(.*)$'
    replace:  '\1Options\2 -IncludesNoExec'
  tags:
    - cat1
    - V-13733

- name: "HIGH | V-13733 | Server Side Includes (SSIs) must be run with execution capability disabled. Remove extra '-IncludesNoExec'"
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   '(\s+)Options(.*)(-IncludesNoExec -IncludesNoExec)'
    replace:  '\1Options\2 -IncludesNoExec'
  tags:
    - cat1
    - V-13733

- name: "HIGH | V-13733 | Server Side Includes (SSIs) must be run with execution capability disabled. Remove 'Includes'."
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   '^(\s+)Options(.*)(\sIncludes\s)(.*)'
    replace:  '\1Options \2 \4'
  tags:
    - cat1
    - V-13733

- name: "HIGH | V-13733 | Server Side Includes (SSIs) must be run with execution capability disabled. Remove '+Includes'."
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   '^(\s+)Options(.*)(\s\+Includes\s)(.*)'
    replace:  '\1Options \2 \4'
  tags:
    - cat1
    - V-13733

- name: "HIGH | V-13733 | Server Side Includes (SSIs) must be run with execution capability disabled. Remove bare 'IncludesNoExec'."
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   '^(\s+)Options(.*)(\sIncludesNoExec\s)(.*)'
    replace:  '\1Options \2\4'
  tags:
    - cat1
    - V-13733

- name: "HIGH | V-2246 | Web server software must be a vendor supported version."
  yum:
    name:   "*"
    state:  latest
  tags:
    - cat1
    - V-2246

- name: "HIGH | V-2258 | Web client access to the content directories must be restricted to read and execute. Directory."
  file:
    path:     /var/www/html
    state:    directory
    owner:    root
    group:    root
    mode:     0755
    recurse:  true

- name: "HIGH | V-2258 | Web client access to the content directories must     be restricted to read and execute. File." 
  shell: find /var/www/html -type f -exec chmod 0644 {} \;

