
- name: "MED | V-2225 | MIME types for csh and shell programs must be disabled."
  replace:  
    path:     "{{ httpd_conf_file }}"
    regexp:   "^(\\s+)AddHandler(\\s+)([a-z-]*)(\\s+){{ item }}(\\s)"
    replace:  "\\1#  AddHandler  \\2 \\3 {{ item }} \n"
  with_items:
    - '.csh'
    - '.sh'
    - '.bash'
    - '.ksh'
  tags:
    - cat2
    - V-2225

- name: "MED | V-13613 | The Web site software used with the web server must have all applicable security patches applied and documented."
  yum:
    name:   "*"
    state:  latest
  tags:
    - cat2
    - V-13613

- name: "MED | V-13724 | The Timeout directive must be properly set."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  present
    regexp: "^Timeout "
    line:   "Timeout {{ timeout_time }}"
  tags:
    - cat2
    - V-13724

- name: "MED | V-26287 | Web Distributed Authoring and Versioning (WebDAV) must be disabled."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'dav_module'
    - 'dav_fs_module'
    - 'dav_lock_module'
  tags:
    - cat2
    - V-26287

- name: "MED | V-26294 | Web server status module must be disabled"
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'info_module'
    - 'status_module'
  tags:
    - cat2
    - V-26294

- name: "MED | V-26299 | The web server must not be configured as a proxy server."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'proxy_module'
    - 'proxy_ajp_module'
    - 'proxy_balancer_module'
    - 'proxy_ftp_module'
    - 'proxy_http_module'
    - 'proxy_connect_module'
  tags:
    - cat2
    - V-26299
    
- name: "MED | V-26302 | User specific directories must not be globally enabled."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'userdir_module'
  tags:
    - cat2
    - V-26302
    
- name: "MED | V-26368 | Automatic directory indexing must be disabled."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'autoindex_module'
  tags:
    - cat2
    - V-26368
  
   
   
