
- name: "MED | V-2225 | MIME types for csh and shell programs must be disabled."
  replace:  
    path:     "{{ httpd_conf_file }}"
    regexp:   "^(\\s+)AddHandler(\\s+)([a-z-]*)(\\s+){{ item }}(\\s)"
    replace:  "\\1#  AddHandler  \\2 \\3 {{ item }} \n"
  with_items:
    - '.csh'
    - '.sh'
    - '.bash'
    - '.ksh'
  tags:
    - cat2
    - V-2225

- name: "MED | V-2255 | The web server’s htpasswd files (if present) must reflect proper ownership and permissions"
  file:
    path:   /usr/bin/htpasswd
    mode:   0550
  tags:
    - cat2
    - V-2255

- name: "MED | V-2256 | The access control files are owned by a privileged web server account."
  file:
    path:   /etc/httpd/conf/httpd.conf
    mode:   0660
    owner:  root
    group:  root
  tags:
    - cat2
    - V-2256
- name: "MED | V-13613 | The Web site software used with the web server must have all applicable security patches applied and documented."
  yum:
    name:   "*"
    state:  latest
  tags:
    - cat2
    - V-13613

- name: "MED | V-13724 | The Timeout directive must be properly set."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  present
    regexp: "^Timeout "
    line:   "Timeout {{ timeout_time }}"
  tags:
    - cat2
    - V-13724

- name: "MED | V-13725 | The KeepAlive directive must be enabled."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  present
    regexp: "^KeepAlive "
    line:   "KeepAlive On"
  tags:
    - cat2
    - V-13725

- name: "MED | V-13726 | The KeepAliveTimeout directive must be defined."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  present
    regexp: "^KeepAliveTimeout "
    line:   "KeepAliveTimeout {{ keepalivetimeout }}"
  tags:
    - cat2
    - V-13726

- name: "MED | V-13727 | The httpd.conf StartServers directive must be set properly." 
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   "^StartServers (.*)$"
    replace:  "StartServers {{ startservers }} "
  tags:
    - cat2
    - V-13727

- name: "MED | V-13728 | The httpd.conf MinSpareServers directive must be set properly."
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   "^MinSpareServers (.*)$"
    replace:  "MinSpareServers {{ minspareservers }} "
  tags:
    - cat2
    - V-13728

- name: "MED | V-13730 | The httpd.conf MaxClients directive must be set properly."
  replace:
    path:     "{{ httpd_conf_file }}"
    regexp:   "^MaxClients (.*)$"
    replace:  "MaxClients {{ maxclients }} "
  tags:
    - cat2
    - V-13730

- name: "MED | V-26287 | Web Distributed Authoring and Versioning (WebDAV) must be disabled."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'dav_module'
    - 'dav_fs_module'
    - 'dav_lock_module'
  tags:
    - cat2
    - V-26287

- name: "MED | V-26294 | Web server status module must be disabled"
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'info_module'
    - 'status_module'
  tags:
    - cat2
    - V-26294

- name: "MED | V-26299 | The web server must not be configured as a proxy server."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'proxy_module'
    - 'proxy_ajp_module'
    - 'proxy_balancer_module'
    - 'proxy_ftp_module'
    - 'proxy_http_module'
    - 'proxy_connect_module'
  tags:
    - cat2
    - V-26299
    
- name: "MED | V-26302 | User specific directories must not be globally enabled."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'userdir_module'
  tags:
    - cat2
    - V-26302
    
- name: "MED | V-26368 | Automatic directory indexing must be disabled."
  lineinfile:
    path:   "{{ httpd_conf_file }}"
    state:  absent
    regexp: "^LoadModule {{ item }}"
  with_items:
    - 'autoindex_module'
  tags:
    - cat2
    - V-26368
  
   
   
