
- name: "LOW | V-6724 | Web server and/or operating system information must be protected."
  lineinfile:    
    path:   "{{ httpd_conf_file }}"
    regexp: "^ServerTokens "
    line:   "ServerTokens Prod"
    state:  present
  tags:
    - cat3
    - V-6724


