
# Install latest httpd
- name: yum_latest_apache
  yum:
    name:   "httpd"
    state:  "latest" 
  when: ansible_distribution_major_version == '6' 

- name: dnf_latest_apache
  dnf:
    name:   "httpd"
    state:  "latest" 
  when: ansible_distribution_major_version == '7' 

- name: copy_in_stig_compliant_httpd_conf
  copy:
    src:    httpd.conf.base
    dest:   /etc/httpd/conf/httpd.conf
    owner:  root
    group:  root
    mode:   0644
